## site variables
timezone: Asia/Tokyo
reveal_path: /reveal.js/
reveal_theme_path: /reveal.js/dist/theme/
markdown: Bypass
## plugins to enable
##plugins:
##  - 
## collections: start with _
collections:
  tips:
    output: true
## files not to be hosted
exclude:
  - Gemfile*
  - .gitmodules
  - LICENSE
  - README.md
  - vendor
  - _scripts
## files to be converted
##include:
##  - some
## files keep as is
keep_files:
  - reveal.js
## page variables set by default
defaults:
  -
    scope:
      path: ""
    values:
      title: ADS
      layout: reveal
      theme: black
      transition: default
      markdown: kramdown
      highlighter: rouge
      markdown_ext: ignoreme
      bypass: false
  -
    scope:
      path: ""
      type: tips
    values:
      bypass: true
      layout: reveal
      theme: night
      transition: slide
