reveal_transition: default
reveal_path: reveal.js/
reveal_theme_path: reveal.js/dist/theme/
exclude:
  - Gemfile*
  - LICENSE
  - README.md

defaults:
  -
    scope:
      path: ""
    values:
      title: ADS
      layout: "reveal"
      reveal_theme: night
      markdown: kramdown
      highlighter: rouge
      markdown_ext: ignoreme
