## site variables
reveal_path: /reveal.js/
reveal_theme_path: /reveal.js/dist/theme/
## files not to be hosted
exclude:
  - Gemfile*
  - .gitmodules
  - LICENSE
  - README.md
  - vendor
  - _scripts
## files to be converted
include:
  - _tips
## files keep as is
keep_files:
  - slides
  - reveal.js
## page variables set by default
defaults:
  -
    scope:
      path: ""
    values:
      title: ADS
      layout: "reveal"
      theme: "black"
      transition: default
      markdown: kramdown
      highlighter: rouge
      markdown_ext: ignoreme
